export const SUPABASE_URL = 'https://lxxicghnzniegdnvtsrk.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4eGljZ2huem5pZWdkbnZ0c3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNjM2NDEsImV4cCI6MjA4MjkzOTY0MX0.pGgGrsDZhicuPLdEKIt2e4f-q35V-nKi5WhGKwM2BUg';
